#!/bin/bash

sleep 1
g++ test2.c -o test2
echo "Running test 2"
./test2
sleep 1
i=1
prv_line=""
while read line; do
if (($i != 1 )); then
	if (( $prv_line > $line)); then
		echo "process do not run in ascending pid order"
		exit
	fi
fi
i=$i+1
prv_line=$line
done < test2.txt
echo "Test 2 passed"
sleep 1
echo "wide awake!"
g++ test3.c -o test3
echo "Running test 3"
./test3
echo test3 run is done
sleep 1
i=1
prv_line=""
while read line; do
if (($i != 1 )); then
	if (( $prv_line < $line)); then
		echo "waiting process do not count in smallest pid count"
		exit
	fi
fi
i=$i+1
prv_line=$line
done < test3.txt
echo "Test 3 passed"

sleep 1
g++ test4.c -o test4
